server:
  port: 8080

spring:
  datasource:
    username: root
    password: Gslsuhtpl-43
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
<<<<<<< HEAD
    show-sql: false

indexing-settings:
  sites:
    - url: https://et-cetera.ru/mobile/
      name: Театр «Et Cetera»

jsoup-setting:
  jsoup:
    timeout: 1000
    userAgent: "Mozilla/5.0 (Windows; U; WindowsNT5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
    referrer: "http://www.google.com"
    ignoreHttpErrors: true
    ignoreContentType: true
    followRedirects: false
=======
    show-sql: true

indexing-settings:
  sites:
    - url: http://avia-simply.ru
      name: Авиация, понятная всем
    - url: https://www.lenta.ru
      name: Лента.ру
>>>>>>> origin/final-project
