version: '3.1'

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "db_searchengine"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "654321"
    volumes:
      - ./db:/var/lib/mysql
volumes:
  db-data:
